version: 2
jobs:
  build:
    #working_directoyr: ~/projects/CItest
    docker:
      - image: circleci/python:3.6
    steps:
      # ソースコードのチェックアウト
      - checkout
      # unittestコマンドの実行
      - run: python test_calculations.py
      #- run: echo "this is the test job"
      #- run: python ~/projects/CItest/test_calculations.py

